name: mybaby_mobile
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.8.2+3
  firebase_auth: ^0.6.6
  google_sign_in: ^3.2.4
  flutter_redux: ^0.5.2
  redux_logging: ^0.3.0
  redux: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
